



# Generated by Django 4.1.7 on 2023-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
